FROM ubuntu
MAINTAINER grunwald@cs.colorado.edu

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    make cmake runit \
    automake \
    gcc \
    gcc-multilib \
    build-essential \
    g++ \
    cpp \
    libc6-dev libtool \
    man-db \
    autoconf automake make \
    git-core \
    pkg-config \
    python
